package br.com.voidling.entities;

import br.com.voidling.graphics.Sprite;
import br.com.voidling.main.Game;

import java.awt.*;

public class Lifepack extends Entity {
    public int health = 25; // the amount of health to be regenerated by it
    public Lifepack(int x, int y) {
        super(x, y, Game.spriteSize, Game.spriteSize, Sprite.LIFEPACK_SPRITE.getSprite());
    }

    /* this returns how much health will be regenerated from the lifepack but before it deactivates the entity */
    public int collect() {
        if (!active) return 0;
        setActive(false);
        return health;
    }
}
